function [ X,Y ] = body( Z,SIGN,TAU,EPSMAX,NACA,PTMAX)
%RETURN COORDINATES OF POINT ON BODY SURFACE
%   Z=NODE-SPACING PARAMETER
%   X,Y=CARTESIAN COORDINATES
%   SIGN=+1 FOR UPPER SURFACE
%       =-1 FOR LOWER SURFACE

if (SIGN<0)
    Z=1-Z;
end
[THICK,CAMBER,BETA]=NACA45(Z,TAU,EPSMAX,NACA,PTMAX);
% X=c*(-XR+Z-SIGN*THICK*sin(BETA));
X=Z-SIGN*THICK*sin(BETA);
Y=CAMBER+SIGN*THICK*cos(BETA);



end

